import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
return (
  <html lang="pt-br" className={inter.variable}>
    <body className="min-h-full flex">
      <Sidebar />
      <div className="flex flex-col flex-1">
        <Header  />
      </div>
      <main>{children}</main>
    </body>
  </html>
);
}
